[WIP] Data complete and restart request
openstack-charmers/charm-interface-keystone-fid-service-provider pull request #1
Opened 2019-03-22 15:02 UTC by thedac

WIP do not merge yet

2019-03-22 15:38 UTC, fnordahl commented on provides.py
> +    # Do auto_accessors work with endpoints?
Unfortunately no.  What you can do instead is just add a property decorated function that gets and returns the data you need access to.  This will be exposed and usable both in the charm code through the ``with provide_charm_instance()`` helper and rendered in config rendering with interfaces (this code here does the latter: https://github.com/openstack/charms.openstack/blob/3e9f4096f9a585e44c0a800ddac914633316c3cc/charms_openstack/adapters.py#L138)

2019-03-22 15:38 UTC, fnordahl commented on provides.py
> +        set_flag(self.expand_name('{endpoint_name}.connected'))
This is the way I have gone about it too, that will make the ``charms.openstack`` assess_status functions work as you would expect.

2019-03-22 15:38 UTC, fnordahl commented on provides.py
> +    def data_complete(self):
Here is a alternative way of doing this: https://github.com/openstack/charm-interface-ceph-rbd-mirror/blob/2677eb3a2ff2505d6dd5f4b75a3bf0a1bf16b10f/requires.py#L55

2019-03-22 15:42 UTC, fnordahl commented on provides.py
> +    # Do auto_accessors work with endpoints?
Example of property that gets relation data from Endpoint class: https://github.com/openstack/charm-interface-ceph-rbd-mirror/blob/2677eb3a2ff2505d6dd5f4b75a3bf0a1bf16b10f/requires.py#L152

2019-03-25 13:55 UTC, fnordahl requested changes

2019-03-25 13:55 UTC, fnordahl commented on provides.py
> +from charms.reactive import (
:+1: Here you need to write it this way as the reactive framework has issues with using it's decorator on class methods if you don't.

2019-03-25 13:55 UTC, fnordahl commented on provides.py
> +        return self.all_joined_units.received['tls-enabled']
:+1:

2019-03-25 13:55 UTC, fnordahl commented on provides.py
> +        self.update_flags()
It is the interfaces job to clear the *.changed flags when you have dealt with them [0].

0: https://charmsreactive.readthedocs.io/en/latest/managed-flags.html#

2019-03-25 13:55 UTC, fnordahl commented on provides.py
> +        }
The same could for example be expressed as:

    @when_all('{endpoint_name}.changed.hostname',
              '{endpoint_name}.changed.port,
              '{endpoint_name}.changed.tls-enabled')
    def data_complete(self):
        # optionally validate that the data is actually sane
        # clear the changed flags
        # set 'available' state
        # ???
        # profit!

2019-03-27 10:10 UTC, ajkavanagh reviewed
Minor nitpick, but otherwise great.

2019-03-27 10:10 UTC, ajkavanagh commented on provides.py
> +            for flag in (flags):
I think the parenthesis here aren't needed?

2019-03-28 12:58 UTC, fnordahl approved these changes
LGTM, thanks!

2019-03-28 12:59 UTC, merged